### ISSUE TITLE
Starting, but drawing window not working

### ISSUE THREAD

**Issue by SienceMC** [SilvanKohler/MS-Paint-shit-edition#5]
**Describe the bug**
This Bug does not allow Drawing in the App at all.

**To Reproduce**
1. Start the Program
2. See error

**Expected behavior**
You should be able to Draw

**Error**

```
Exception in thread Thread-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\....\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
  File "paint.py", line 139, in <module>
    mainprocess.run()
    self.run()
  File "paint.py", line 105, in run
  File "paint.py", line 51, in run
    positioningQAB.rect = rect
NameError: name 'positioningQAB' is not defined
    QAB.process.communicate((self.rect.left, self.rect.top - settings['quickAccessBarWindowSize']['heigth']))
AttributeError: 'NoneType' object has no attribute 'communicate'
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by SilvanKohler** [comment]
fixed in c70d1ca
